# Generated by Django 5.2.5 on 2025-09-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcoins',
            name='test',
            field=models.IntegerField(null=True),
        ),
    ]
