# Generated by Django 5.2.5 on 2025-09-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accountcoins_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcoins',
            name='test',
        ),
    ]
